DROP TABLE IF EXISTS MISSION;
DROP TABLE IF EXISTS MISSION_ICON;
DROP TABLE IF EXISTS ICON_CATEGORY;
DROP TABLE IF EXISTS ROUTINE_SET;
DROP TABLE IF EXISTS ROUTINE;
DROP TABLE IF EXISTS REPLY;
DROP TABLE IF EXISTS BOARD_IMAGE;
DROP TABLE IF EXISTS BOARD;
DROP TABLE IF EXISTS MEMBER;

INSERT INTO MEMBER (BIRTH,EMAIL,GENDER,JOIN_DATE,LEVEL,NICKNAME,PWD) VALUES('1994-07-02', 'hirokazu@gmail.com', 'M', NOW(), 'admin', 'HIROKAZU', 'hirokazu7');
INSERT INTO MEMBER (BIRTH,EMAIL,GENDER,JOIN_DATE,LEVEL,NICKNAME,PWD) VALUES('1993-02-14', 'kristal@gmail.com', 'F', NOW(), 'admin', 'KRISTAL', 'kristal1');
INSERT INTO ICON_CATEGORY(CATEGORY_NAME, PAY) VALUES('logo', FALSE);
INSERT INTO MISSION_ICON(ICON_FILE_NAME, ICON_CATEGORY_ID) VALUES('favicon.png', 1);
