DROP TABLE IF EXISTS `BOARD`;

CREATE TABLE `BOARD` (
	`BOARDNUM`	INTEGER	NOT NULL,
	`IDX`	INTEGER	NOT NULL,
	`CATEGORYNAME`	VARCHAR(20)	NOT NULL,
	`BOARDTITLE`	VARCHAR(200)	NULL,
	`BOARDCONTENT`	VARCHAR(4096)	NULL,
	`BOARDCREATE`	DATETIME	NULL,
	`BOARDMODIFY`	DATETIME	NULL,
	`BOARDHITS`	INTEGER	NULL
);

DROP TABLE IF EXISTS `MEMBER`;

CREATE TABLE `MEMBER` (
	`IDX`	INTEGER	NOT NULL,
	`ID`	VARCHAR(20)	NULL,
	`PWD`	VARCHAR(20)	NULL,
	`NICKNAME`	VARCHAR(20)	NULL,
	`GENDER`	VARCHAR(10)	NULL,
	`BIRTH`	DATE	NULL,
	`GRADE`	VARCHAR(20)	NULL,
	`JOINDATE`	DATETIME	NULL,
	`LASTDATE`	DATETIME	NULL
);

DROP TABLE IF EXISTS `BOARDIMAGE`;

CREATE TABLE `BOARDIMAGE` (
	`IMAGENUM`	INTEGER	NOT NULL,
	`BOARDNUM`	INTEGER	NOT NULL,
	`IMAGEFILENAME`	VARCHAR(50)	NULL
);

DROP TABLE IF EXISTS `REPLY`;

CREATE TABLE `REPLY` (
	`REPLYNUM`	INTEGER	NOT NULL,
	`IDX`	INTEGER	NOT NULL,
	`BOARDNUM`	INTEGER	NOT NULL,
	`REPLYCONTENT`	VARCHAR(1024)	NULL,
	`REPLYCREATE`	DATETIME	NULL
);

DROP TABLE IF EXISTS `ROUTINE`;

CREATE TABLE `ROUTINE` (
	`ROUTINENUM`	INTEGER	NOT NULL,
	`IDX`	INTEGER	NOT NULL,
	`ROUTINENAME`	VARCHAR(50)	NULL,
	`ACTIVEORNOT`	BOOLEAN	NULL,
	`COMPLETEORNOT`	BOOLEAN	NULL,
	`TOTALTIME`	TIME	NULL
);

DROP TABLE IF EXISTS `MISSION`;

CREATE TABLE `MISSION` (
	`MISSIONNUM`	INTEGER	NOT NULL,
	`ROUTINENUM`	INTEGER	NOT NULL,
	`ICONNUM`	INTEGER	NOT NULL,
	`MISSIONNAME`	VARCHAR(50)	NULL,
	`RUNTIME`	TIME	NULL,
	`MISSIONCONTENT`	VARCHAR(200)	NULL
);

DROP TABLE IF EXISTS `ICONMISSION`;

CREATE TABLE `ICONMISSION` (
	`ICONNUM`	INTEGER	NOT NULL,
	`CATEGORYNAME`	VARCHAR(50)	NULL,
	`ICONFILENAME`	VARCHAR(50)	NULL
);

DROP TABLE IF EXISTS `ROUTINESET`;

CREATE TABLE `ROUTINESET` (
	`ROUTINENUM`	INTEGER	NOT NULL,
	`WEEK`	INTEGER	NULL,
	`STARTTIME`	TIME	NULL
);

DROP TABLE IF EXISTS `ICONCATEGORY`;

CREATE TABLE `ICONCATEGORY` (
	`CATEGORYNAME`	VARCHAR(50)	NULL,
	`CATEGORYORDER`	INTEGER	NULL,
	`PAYORNOT`	BOOLEAN	NULL
);

DROP TABLE IF EXISTS `BOARDCATEGORY`;

CREATE TABLE `BOARDCATEGORY` (
	`CATEGORYNAME`	VARVHAR(20)	NOT NULL,
	`Field`	VARCHAR(255)	NULL
);

ALTER TABLE `BOARD` ADD CONSTRAINT `PK_BOARD` PRIMARY KEY (
	`BOARDNUM`,
	`IDX`,
	`CATEGORYNAME`
);

ALTER TABLE `MEMBER` ADD CONSTRAINT `PK_MEMBER` PRIMARY KEY (
	`IDX`
);

ALTER TABLE `BOARDIMAGE` ADD CONSTRAINT `PK_BOARDIMAGE` PRIMARY KEY (
	`IMAGENUM`,
	`BOARDNUM`
);

ALTER TABLE `REPLY` ADD CONSTRAINT `PK_REPLY` PRIMARY KEY (
	`REPLYNUM`,
	`IDX`,
	`BOARDNUM`
);

ALTER TABLE `ROUTINE` ADD CONSTRAINT `PK_ROUTINE` PRIMARY KEY (
	`ROUTINENUM`,
	`IDX`
);

ALTER TABLE `MISSION` ADD CONSTRAINT `PK_MISSION` PRIMARY KEY (
	`MISSIONNUM`,
	`ROUTINENUM`,
	`ICONNUM`
);

ALTER TABLE `ICONMISSION` ADD CONSTRAINT `PK_ICONMISSION` PRIMARY KEY (
	`ICONNUM`,
	`CATEGORYNAME`
);

ALTER TABLE `ROUTINESET` ADD CONSTRAINT `PK_ROUTINESET` PRIMARY KEY (
	`ROUTINENUM`
);

ALTER TABLE `ICONCATEGORY` ADD CONSTRAINT `PK_ICONCATEGORY` PRIMARY KEY (
	`CATEGORYNAME`
);

ALTER TABLE `BOARDCATEGORY` ADD CONSTRAINT `PK_BOARDCATEGORY` PRIMARY KEY (
	`CATEGORYNAME`
);

ALTER TABLE `BOARD` ADD CONSTRAINT `FK_MEMBER_TO_BOARD_1` FOREIGN KEY (
	`IDX`
)
REFERENCES `MEMBER` (
	`IDX`
);

ALTER TABLE `BOARD` ADD CONSTRAINT `FK_BOARDCATEGORY_TO_BOARD_1` FOREIGN KEY (
	`CATEGORYNAME`
)
REFERENCES `BOARDCATEGORY` (
	`CATEGORYNAME`
);

ALTER TABLE `BOARDIMAGE` ADD CONSTRAINT `FK_BOARD_TO_BOARDIMAGE_1` FOREIGN KEY (
	`BOARDNUM`
)
REFERENCES `BOARD` (
	`BOARDNUM`
);

ALTER TABLE `REPLY` ADD CONSTRAINT `FK_MEMBER_TO_REPLY_1` FOREIGN KEY (
	`IDX`
)
REFERENCES `MEMBER` (
	`IDX`
);

ALTER TABLE `REPLY` ADD CONSTRAINT `FK_BOARD_TO_REPLY_1` FOREIGN KEY (
	`BOARDNUM`
)
REFERENCES `BOARD` (
	`BOARDNUM`
);

ALTER TABLE `ROUTINE` ADD CONSTRAINT `FK_MEMBER_TO_ROUTINE_1` FOREIGN KEY (
	`IDX`
)
REFERENCES `MEMBER` (
	`IDX`
);

ALTER TABLE `MISSION` ADD CONSTRAINT `FK_ROUTINE_TO_MISSION_1` FOREIGN KEY (
	`ROUTINENUM`
)
REFERENCES `ROUTINE` (
	`ROUTINENUM`
);

ALTER TABLE `MISSION` ADD CONSTRAINT `FK_ICONMISSION_TO_MISSION_1` FOREIGN KEY (
	`ICONNUM`
)
REFERENCES `ICONMISSION` (
	`ICONNUM`
);

ALTER TABLE `ICONMISSION` ADD CONSTRAINT `FK_ICONCATEGORY_TO_ICONMISSION_1` FOREIGN KEY (
	`CATEGORYNAME`
)
REFERENCES `ICONCATEGORY` (
	`CATEGORYNAME`
);

ALTER TABLE `ROUTINESET` ADD CONSTRAINT `FK_ROUTINE_TO_ROUTINESET_1` FOREIGN KEY (
	`ROUTINENUM`
)
REFERENCES `ROUTINE` (
	`ROUTINENUM`
);

